--drop table FRIENDSHIP cascade;
--drop table LIKES cascade;
-- drop table FILMS cascade;
-- drop table FILM_GENRE cascade;
-- drop table GENRE cascade;
-- drop table USERS cascade;

CREATE TABLE FILMS (
    FILM_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITLE CHARACTER VARYING(40) NOT NULL,
    DESCRIPTION CHARACTER VARYING NOT NULL,
    RELEASE_DATE DATE,
    DURATION INTEGER,
    RATE INTEGER,
    MPA_RATING CHARACTER VARYING
);

create table USERS
(
    USER_ID  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EMAIL    CHARACTER VARYING,
    LOGIN    CHARACTER VARYING,
    NAME     CHARACTER VARYING,
    BIRTHDAY DATE
);

create table FILM_GENRE
(
    FILM_ID  INTEGER auto_increment unique not null,
    GENRE_ID INTEGER,
    constraint FILM_GENRE_PK
        primary key (FILM_ID)
);

create table GENRE
(
    GENRE_ID    INTEGER not null,
    GENRE_NAME CHARACTER VARYING,
    constraint GENRE_PK
        primary key (GENRE_ID)
);

create table FRIENDSHIP
(
    USER_ID   INTEGER not null,
    FRIEND_ID INTEGER,
    constraint FRIENDSHIP_PK
        primary key (USER_ID)

);

create table LIKES
(
    FILM_ID INTEGER not null,
    USER_ID INTEGER,
    constraint LIKES_PK
        primary key (FILM_ID)
);

alter table LIKES
    add constraint LIKES_USERS_USER_ID_FK
        foreign key (USER_ID) references USERS;

alter table LIKES
    add constraint LIKES_FILMS_ID_FK
        foreign key (FILM_ID) references FILMS;

alter table FRIENDSHIP
    add constraint FRIENDSHIP_USERS_USER_ID_FK
        foreign key (USER_ID) references USERS;

alter table FILM_GENRE
    add constraint FILM_GENRE_GENRE_GENRE_ID_FK
        foreign key (GENRE_ID) references GENRE;

alter table FILMS
    alter column FILM_ID INTEGER auto_increment;

alter table FILMS
    add constraint FILMS_FILM_GENRE_FILM_ID_FK
        foreign key (FILM_ID) references FILM_GENRE;